### ISSUE TITLE
doesn't escape ANSI escape codes

### ISSUE THREAD

**Issue by dmitriiabramov** [thejameskyle/pretty-format#18]
`prettyFormat(require('chalk'))` will give you a nice rainbow :)
![screen shot 2016-07-05 at 5 45 17 pm](https://cloud.githubusercontent.com/assets/940133/16604305/bf893ad8-42d8-11e6-96f6-a4b5a57c8421.png)

not sure if it's expected behavior or not. If not i can look into it

**Comment by thejameskyle** [comment]
`console.log` the rainbow, taste the rainbow

**Comment by thejameskyle** [comment]
I don't know, should it be modifying strings at all? @cpojer?

**Comment by cpojer** [comment]
I'm not entirely convinced this is something that pretty-format should account for.
