### ISSUE TITLE
Array values not passed through plugins?

### ISSUE THREAD

**Issue by developit** [thejameskyle/pretty-format#24]
Hi @thejameskyle - this is a great module! I'm working on integrating it into [preact-render-to-string](https://github.com/developit/preact-render-to-string) for better JSX assertions.  I ran into something odd: when values are contained in an Array, it seems like plugins are never invoked on them.

Here's a minimal repro of what I'm running into:  https://jsfiddle.net/developit/t7p0abzc/

In that demo, the `"b"` attribute is an Array of two `VNode` instances.  If I'm understanding pretty-format correctly, the Array should be handled by `printArray()`/`printList()`, and each value in the Array should be passed through `printPlugin()`.

In my quick glance through the library, it seems like the invocation of `printPlugin()` needs to be done from `printComplexValue()` instead of from `prettyFormat()`. Does that seem reasonable?

If it helps, I have this on a branch, where you can see I have to add manual support for Arrays of VNodes to the plugin: https://github.com/developit/preact-render-to-string/blob/pretty-format/src/index.js#L93-L112

**Comment by thejameskyle** [comment]
Fixed

**Comment by developit** [comment]
Works like a charm, thanks!
