### ISSUE TITLE
Immutable.js objects are printed as simple data structures

### ISSUE THREAD

**Issue by dmitriiabramov** [thejameskyle/pretty-format#32]
https://github.com/facebook/jest/issues/1622

```
> Immutable = require('immutable'); format = require('pretty-format');
[Function: prettyFormat]
> format(Immutable.List([1, 2, 3]));
'Array [\n  1,\n  2,\n  3\n]'
> format([1, 2, 3]);
'Array [\n  1,\n  2,\n  3\n]'
>
```

Expected behavior is probably to have it printed as `List [1, 2, 3]`.

it happens because there's a `.toJSON` called on values if it's present.

**Comment by cpojer** [comment]
What does it print if we don't call toJSON on immutable objects? Should we have a plugin for immutable?

**Comment by dmitriiabramov** [comment]
it will print
```js
> console.log(format(l))
List {
  "__altered": false,
  "__hash": undefined,
  "__ownerID": undefined,
  "_capacity": 3,
  "_level": 5,
  "_origin": 0,
  "_root": null,
  "_tail": VNode {
    "array": Array [
      1,
      2,
      3
    ],
    "ownerID": undefined
  },
  "size": 3
}
```

we can make a plugin, or we can try to pass the original `constructor` function along with jsonified value (which will leak into every function as an additional argument)

if we make a plugin, it probably makes sense to expose simple util function like `printList, printMap, ...` to the outside world

**Comment by cpojer** [comment]
I think a plugin makes the most sense then? We don't want to print all those private fields.

**Comment by dmitriiabramov** [comment]
i can make it a plugin. Can i move `printList, printMap` and others into a separate `utils.js` though?

**Comment by cpojer** [comment]
sure!

**Comment by cpojer** [comment]
We just merged pretty-format into Jest. Please follow-up in the Jest repo: https://github.com/facebook/jest/pull/2300
