### ISSUE TITLE
Help with plugin to frozen Date and Object Id of mongoose object

### ISSUE THREAD

**Issue by sibelius** [thejameskyle/pretty-format#33]
I want to create a plugin to pretty-format to replace a field that is a date of a mongoose object to a placeholder string

```js
const frozenDate = {
  test: (val) => {
    let temp;
    if (val instanceof Date) {
      temp = val;
    } else {
      temp = new Date(val)
    }

    return isNaN(temp.getTime()) === false;
  },
  print: (val, print, indent) => {
    return 'FAKE-DA-TET00:00:00.000Z';
  }
};
```

the idea is to replace createdAt and updatedAt of mongoose objects to be able to snapshot test them using jest

this is what I did to handle objectID changing, and it is working

```js
let counter = 0;
let objectIdToNumber = {};

const objectIdPlugin = {
  test: (val) => {
    return val != 0 && ObjectId.isValid(""+val);
  },
  print: (val, print, indent) => {
    if (val in objectIdToNumber) {
    } else {
      objectIdToNumber[val] = counter;
      counter++;
    }

    const internalId = objectIdToNumber[val];

    return `OBJECT_${internalId}`;
  }
};
```

this is how I'm using prettyFormat:

```js
prettyFormat(val, {
   plugins: [objectIdPlugin, frozenDate]
})
```

the `test` function of the plugins are only called in an object not inside its properties

**Comment by cpojer** [comment]
I recommended on the #jest discord channel to instead prepare the object before passing it on to Jest's matcher.
