### ISSUE TITLE
Don’t reject unknown options

### ISSUE THREAD

**Issue by jmakeig** [thejameskyle/pretty-format#37]
`validateOptions()` rejects keys that aren’t in the defaults. This makes extensibility more difficult. For example, I have a wrapper function that post-processes the output of pretty-format. It provides the same signature as pretty-format and reuses (hijacks?) the `opts` object with some extra stuff, germane only to the wrapper. It would be more convenient to be able just to pass these options through, rather than having to prune them first.

I’ll try to create a PR.

**Comment by thejameskyle** [comment]
I generally would prefer if you just only passed valid options to pretty-format. I think it's better to have an enforced public api so that I can control what breaking changes are.

**Comment by jmakeig** [comment]
I can buy that. The work-around isn’t too painful:

```javascript
const format = require('pretty-format');

function prettyFormat(val, opts) {
  const myStuff = opts.myStuff;
  delete opts.myStuff;
  …
  const formatted = format(val, opts);
  …
  return myFormatter(formatted, myStuff);
}

module.exports = prettyFormat;
```
