### ISSUE TITLE
Support for Object.create(null)

### ISSUE THREAD

**Issue by osi-oswald** [thejameskyle/pretty-format#42]
In ES5, where [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) is not available, some use `Object.create(null)` as a Map container instead. 

Unfortunately the output for plain Objects `{}` and Objects created via `Object.create(null)` are the same with prettyFormat: `Object {}`.

I would expect the output for Objects created via `Object.create(null)` to be different:
maybe either `null {}` or even just `{}`, since there is no constructor/prototype.

**Comment by cpojer** [comment]
See PR.
