### ISSUE TITLE
Crashes when given an HTML Element

### ISSUE THREAD

**Issue by davidtheclark** [thejameskyle/pretty-format#44]
The module seems to crash completely when asked to print an `HTMLElement`.

I'll post a PR that adds a test illustrating this.

**Comment by davidtheclark** [comment]
I created a parallel issue in Jest: https://github.com/facebook/jest/issues/2027 Not sure where these projects would place the responsibility. Seems to me Jest should be responsible for figuring out a good way to diff HTML Elements; but that this module shouldn't just crash when handed one.

**Comment by davidtheclark** [comment]
This is probably going to be solved by https://github.com/thejameskyle/pretty-format/pull/47.

**Comment by cpojer** [comment]
We just merged pretty-format into Jest. Please follow-up in the Jest repo: https://github.com/facebook/jest/pull/2300
