### ISSUE TITLE
interactive README

### ISSUE THREAD

**Issue by viebel** [thejameskyle/pretty-format#55]
Very nice library and very useful.

Would you be interested in an interactive version of your README?

Have a look here: http://klipse.ghost.io/p/c0a85ce2-f7f6-45d9-9e6c-df2f85d46897/

The interactive code snippets are powered by a lib of mine - [KLIPSE](github.com/viebel/klipse).

**Comment by viebel** [comment]
It's quite funny, because I'm using `pretty-format` to display the results of javascript evaluation inside KLIPSE...

**Comment by cpojer** [comment]
Thanks! I think we are good for now. This project is really cool though
