### ISSUE TITLE
Colorized output

### ISSUE THREAD

**Issue by vadimdemedes** [thejameskyle/pretty-format#57]
Would be very convenient to have a `colors` option with settings for colorizing the output, which would accept chalk color names as values. For example:

```js
prettyFormat(obj, {
  colors: {
    number: 'yellow',
    string: 'red',
    comma: 'grey',
    bracket: 'grey'
  }
});
```

Note, there are options for colorizing even brackets and commas, not just values. Right now I'm working around this by matching via regex and replacing strings with chalk applied. Obviously, this is not a stable approach and will definitely break at certain value types.

If you are interested in having this feature, I can submit a PR for it. Thank you for a great library!

**Comment by vadimdemedes** [comment]
Somehow I missed `themes` option. These new color options would go to `themes`, rather than `colors`.

**Comment by cpojer** [comment]
We just merged pretty-format into Jest. Please follow-up in the Jest repo: https://github.com/facebook/jest/pull/2300
